[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.sdkconfig = sdkconfig.defaults
board_upload.flash_size = 2MB
monitor_speed = 115200
build_flags =
    -I../../shared/protocol
