#pragma once

#define TEENSY_APP_MODE_LINK_BENCH        0
#define TEENSY_APP_MODE_CAMERA_BRINGUP    1

#ifndef TEENSY_APP_SELECTED_MODE
#define TEENSY_APP_SELECTED_MODE TEENSY_APP_MODE_CAMERA_BRINGUP
#endif
