#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/* Bring up MCAL/RTD drivers generated by the board configuration. */
void Board_InitDrivers(void);

/* Common application hardware init used by full app-style modes. */
void Board_InitCommonApp(void);

#ifdef __cplusplus
}
#endif
